
#CXX=g++
CXX=clang++
#FLAGS=
#FLAGS=-std=c++11
FLAGS=-std=c++14

out.test_returnVectorConversion : test_returnVectorConversion.cpp
	$(CXX) $(FLAGS) -ggdb  -O0 -Wall test_returnVectorConversion.cpp -o out.test_returnVectorConversion

clean:
	rm out.*
