
out.test_entropy : test_entropy.cpp test_access_specifier.cpp
	g++ -ggdb -O0 -Wall -std=c++11 test_entropy.cpp -o out.test_entropy
	g++ -ggdb -O0 -Wall -std=c++11 test_access_specifier.cpp -o out.test_access_specifier

clean: 
	rm out.test_entropy out.test_access_specifier
